---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  template:
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:8.5
        # Remove a seção volumes e volumeMounts
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123"