apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: postgres-bare-metal
  namespace: webcolor
  labels:
    kubernetes.io/service-name: postgres-bare-metal
addressType: IPv4
ports:
  - name: postgresql
    port: 5432
    protocol: TCP
endpoints:
  - addresses:
    - "10.100.0.2"  # ⚠️ SUBSTITUA PELO IP REAL DA SUA VPS

#
    # apiVersion: v1
# kind: Endpoints
# metadata:
#   name: postgres-bare-metal
# subsets:
#   - addresses:
#     - ip: 10.100.0.2  # IP da VPS
#     ports:
#     - port: 5432
#       name: postgresql