---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-bare-metal
# spec:
#   type: ClusterIP
#   ports:
#   - port: 5432
#     targetPort: 5432
apiVersion: v1
kind: Service
metadata:
  name: postgres-bare-metal
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  externalIPs:
  - "10.100.0.2"